//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SuperMagaSales
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Invioce.
    /// </summary>
    // *** Start programmer edit section *** (Invioce CustomAttributes)

    // *** End programmer edit section *** (Invioce CustomAttributes)
    [AutoAltered()]
    [Caption("Накладная")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("InvioceE", new string[] {
            "SalesDate as \'Sales date\'",
            "Client as \'Client\'",
            "Client.Name as \'Name\'"}, Hidden=new string[] {
            "Client.Name"})]
    [AssociatedDetailViewAttribute("InvioceE", "ProductItem", "ProductItemE", true, "", "Product item", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("InvioceE", "Client", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("InvioceL", new string[] {
            "SalesDate as \'Дата продажи\'",
            "Client.Name as \'Клиент\'"})]
    public class Invioce : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fSalesDate;
        
        private IIS.SuperMagaSales.Client fClient;
        
        private IIS.SuperMagaSales.DetailArrayOfProductItem fProductItem;
        
        // *** Start programmer edit section *** (Invioce CustomMembers)

        // *** End programmer edit section *** (Invioce CustomMembers)

        
        /// <summary>
        /// SalesDate.
        /// </summary>
        // *** Start programmer edit section *** (Invioce.SalesDate CustomAttributes)

        // *** End programmer edit section *** (Invioce.SalesDate CustomAttributes)
        public virtual System.DateTime SalesDate
        {
            get
            {
                // *** Start programmer edit section *** (Invioce.SalesDate Get start)

                // *** End programmer edit section *** (Invioce.SalesDate Get start)
                System.DateTime result = this.fSalesDate;
                // *** Start programmer edit section *** (Invioce.SalesDate Get end)

                // *** End programmer edit section *** (Invioce.SalesDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Invioce.SalesDate Set start)

                // *** End programmer edit section *** (Invioce.SalesDate Set start)
                this.fSalesDate = value;
                // *** Start programmer edit section *** (Invioce.SalesDate Set end)

                // *** End programmer edit section *** (Invioce.SalesDate Set end)
            }
        }
        
        /// <summary>
        /// Invioce.
        /// </summary>
        // *** Start programmer edit section *** (Invioce.Client CustomAttributes)

        // *** End programmer edit section *** (Invioce.Client CustomAttributes)
        [PropertyStorage(new string[] {
                "Client"})]
        public virtual IIS.SuperMagaSales.Client Client
        {
            get
            {
                // *** Start programmer edit section *** (Invioce.Client Get start)

                // *** End programmer edit section *** (Invioce.Client Get start)
                IIS.SuperMagaSales.Client result = this.fClient;
                // *** Start programmer edit section *** (Invioce.Client Get end)

                // *** End programmer edit section *** (Invioce.Client Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Invioce.Client Set start)

                // *** End programmer edit section *** (Invioce.Client Set start)
                this.fClient = value;
                // *** Start programmer edit section *** (Invioce.Client Set end)

                // *** End programmer edit section *** (Invioce.Client Set end)
            }
        }
        
        /// <summary>
        /// Invioce.
        /// </summary>
        // *** Start programmer edit section *** (Invioce.ProductItem CustomAttributes)

        // *** End programmer edit section *** (Invioce.ProductItem CustomAttributes)
        public virtual IIS.SuperMagaSales.DetailArrayOfProductItem ProductItem
        {
            get
            {
                // *** Start programmer edit section *** (Invioce.ProductItem Get start)

                // *** End programmer edit section *** (Invioce.ProductItem Get start)
                if ((this.fProductItem == null))
                {
                    this.fProductItem = new IIS.SuperMagaSales.DetailArrayOfProductItem(this);
                }
                IIS.SuperMagaSales.DetailArrayOfProductItem result = this.fProductItem;
                // *** Start programmer edit section *** (Invioce.ProductItem Get end)

                // *** End programmer edit section *** (Invioce.ProductItem Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Invioce.ProductItem Set start)

                // *** End programmer edit section *** (Invioce.ProductItem Set start)
                this.fProductItem = value;
                // *** Start programmer edit section *** (Invioce.ProductItem Set end)

                // *** End programmer edit section *** (Invioce.ProductItem Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "InvioceE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View InvioceE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("InvioceE", typeof(IIS.SuperMagaSales.Invioce));
                }
            }
            
            /// <summary>
            /// "InvioceL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View InvioceL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("InvioceL", typeof(IIS.SuperMagaSales.Invioce));
                }
            }
        }
    }
}
