//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SuperMagaSales
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Product item.
    /// </summary>
    // *** Start programmer edit section *** (ProductItem CustomAttributes)

    // *** End programmer edit section *** (ProductItem CustomAttributes)
    [AutoAltered()]
    [Caption("Product item")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ProductItemE", new string[] {
            "Amount as \'Amount\'",
            "Product as \'Product\'",
            "Product.Name as \'Name\'"}, Hidden=new string[] {
            "Product.Name"})]
    [MasterViewDefineAttribute("ProductItemE", "Product", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class ProductItem : ICSSoft.STORMNET.DataObject
    {
        
        private int fAmount;
        
        private IIS.SuperMagaSales.Product fProduct;
        
        private IIS.SuperMagaSales.Invioce fInvioce;
        
        // *** Start programmer edit section *** (ProductItem CustomMembers)

        // *** End programmer edit section *** (ProductItem CustomMembers)

        
        /// <summary>
        /// Amount.
        /// </summary>
        // *** Start programmer edit section *** (ProductItem.Amount CustomAttributes)

        // *** End programmer edit section *** (ProductItem.Amount CustomAttributes)
        public virtual int Amount
        {
            get
            {
                // *** Start programmer edit section *** (ProductItem.Amount Get start)

                // *** End programmer edit section *** (ProductItem.Amount Get start)
                int result = this.fAmount;
                // *** Start programmer edit section *** (ProductItem.Amount Get end)

                // *** End programmer edit section *** (ProductItem.Amount Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ProductItem.Amount Set start)

                // *** End programmer edit section *** (ProductItem.Amount Set start)
                this.fAmount = value;
                // *** Start programmer edit section *** (ProductItem.Amount Set end)

                // *** End programmer edit section *** (ProductItem.Amount Set end)
            }
        }
        
        /// <summary>
        /// Product item.
        /// </summary>
        // *** Start programmer edit section *** (ProductItem.Product CustomAttributes)

        // *** End programmer edit section *** (ProductItem.Product CustomAttributes)
        [PropertyStorage(new string[] {
                "Product"})]
        [NotNull()]
        public virtual IIS.SuperMagaSales.Product Product
        {
            get
            {
                // *** Start programmer edit section *** (ProductItem.Product Get start)

                // *** End programmer edit section *** (ProductItem.Product Get start)
                IIS.SuperMagaSales.Product result = this.fProduct;
                // *** Start programmer edit section *** (ProductItem.Product Get end)

                // *** End programmer edit section *** (ProductItem.Product Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ProductItem.Product Set start)

                // *** End programmer edit section *** (ProductItem.Product Set start)
                this.fProduct = value;
                // *** Start programmer edit section *** (ProductItem.Product Set end)

                // *** End programmer edit section *** (ProductItem.Product Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.SuperMagaSales.Invioce.
        /// </summary>
        // *** Start programmer edit section *** (ProductItem.Invioce CustomAttributes)

        // *** End programmer edit section *** (ProductItem.Invioce CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Invioce"})]
        public virtual IIS.SuperMagaSales.Invioce Invioce
        {
            get
            {
                // *** Start programmer edit section *** (ProductItem.Invioce Get start)

                // *** End programmer edit section *** (ProductItem.Invioce Get start)
                IIS.SuperMagaSales.Invioce result = this.fInvioce;
                // *** Start programmer edit section *** (ProductItem.Invioce Get end)

                // *** End programmer edit section *** (ProductItem.Invioce Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ProductItem.Invioce Set start)

                // *** End programmer edit section *** (ProductItem.Invioce Set start)
                this.fInvioce = value;
                // *** Start programmer edit section *** (ProductItem.Invioce Set end)

                // *** End programmer edit section *** (ProductItem.Invioce Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ProductItemE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ProductItemE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ProductItemE", typeof(IIS.SuperMagaSales.ProductItem));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ProductItem.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfProductItem CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfProductItem CustomAttributes)
    public class DetailArrayOfProductItem : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.SuperMagaSales.DetailArrayOfProductItem members)

        // *** End programmer edit section *** (IIS.SuperMagaSales.DetailArrayOfProductItem members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ProductItem by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ProductItem.
        /// </summary>
        public DetailArrayOfProductItem(IIS.SuperMagaSales.Invioce fInvioce) : 
                base(typeof(ProductItem), ((ICSSoft.STORMNET.DataObject)(fInvioce)))
        {
        }
        
        public IIS.SuperMagaSales.ProductItem this[int index]
        {
            get
            {
                return ((IIS.SuperMagaSales.ProductItem)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.SuperMagaSales.ProductItem dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
